apiVersion: v1
kind: ConfigMap
metadata:
  name: cwcm
data:
  DB_NAME: "postgresql"
  DB_USERNAME: "dbadmin"
  DB_HOST: "10.100.246.144"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: cws
type: Opaque
data:
  DB_PASSWORD: ZGJwYXNzd29yZA==
